# Generated by Django 4.0.4 on 2022-04-17 11:56

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to=data.models.get_sound_file_path)),
                ('type', models.CharField(max_length=100)),
                ('transcription', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en-US', 'en-US'), ('de-DE', 'de-DE')], max_length=10)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.origin')),
            ],
        ),
    ]
