# Generated by Django 4.0.4 on 2022-04-17 16:54

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_sound_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='rating',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='file',
            field=models.FileField(upload_to=data.models.get_sound_file_path, validators=[data.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='sound',
            name='type',
            field=models.CharField(choices=[('audio/mp3', 'audio/mp3'), ('audio/wav', 'audio/wav')], max_length=30),
        ),
    ]
